### ISSUE TITLE
No such device exists

### ISSUE THREAD

**Issue by tdikun** [kenyonj/dashed#2]
Thank you so much for creating this! I have been getting an error when I attempt to run the executable. 

The SSID for my machine is "Dikun" and the dash is connected to the same network. When I run `sudo find_dash Dikun` the output is

```
/Users/timothydikun/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/dashed-0.3.0/exe/find_dash:9:in `open_live': Dikun: No such device exists (BIOCSETIF failed: Device not configured) (RuntimeError)
    from /Users/timothydikun/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/dashed-0.3.0/exe/find_dash:9:in `<top (required)>'
    from /Users/timothydikun/.rbenv/versions/2.1.5/bin/find_dash:23:in `load'
    from /Users/timothydikun/.rbenv/versions/2.1.5/bin/find_dash:23:in `<main>'
```

Any idea what I'm doing wrong? Thanks.

**Comment by kenyonj** [comment]
You don't want to use the SSID, but rather the network interface name for your wireless card... usually something like `wlan0` or `en1`

**Comment by tdikun** [comment]
Thanks, `en1` did the trick. I am new to Ruby so am having a little difficulty figuring out how to create an application that is able to do something with this. Whenever you get the chance, a demo app would be really helpful. Maybe a simple one that just prints a string to the browser whenever the button is pushed. Thanks!

**Comment by kenyonj** [comment]
The readme shows an example implementation. All you have to do is add the proper `require`s to the top of the file:

``` ruby
require "rubygems"
require "dashed"

Dashed::Button.new("ff:ff:ff:ff:ff:ff", "en1").on_press do
  puts "I was pressed!"
end
```

The `ff:ff:ff:ff:ff:ff` should be the mac address for your button that you found using the `find_button` utility.

**Comment by tdikun** [comment]
Ok, thanks!
